### ISSUE TITLE
Which License to use: MIT or CC-BY 3.0?

### ISSUE THREAD

**Issue by tajmone** [mattgraham/leapday#18]
Both your **Leap Day** and **Midnight** themes have an MIT `LICENSE` file and a CC-BY 3.0 license declaration in the `README.md` file. The GitHub top bar show an MIT License.

Is it a dual license?

I'm about to publish a derivative work from these themes, and I need to know under which license to release it. Which one should I use?

Thanks

**Comment by mattgraham** [comment]
@tajmone i'm sorry I missed this. I believe MIT is the correct license. I'll remove the CC-BY. Thanks for pointing it out and feel free to modify and use away.
