### ISSUE TITLE
New GH Project with Derivate Work of Leap Day

### ISSUE THREAD

**Issue by tajmone** [mattgraham/leapday#19]
Hi @mattgraham, 

just wante to inform you of my new project which includes a derivate of your Leap Day theme:

- https://tajmone.github.io/gh-themes-magick/
- https://github.com/tajmone/gh-themes-magick

Leap Day folder (`LICENSE` and `CHANGELIST` files added):

- https://github.com/tajmone/gh-themes-magick/tree/master/gh-themes/leapday

I hope that everything is fine with license, due credits and mentioning changes done.

B.R.

Tristano

**Comment by mattgraham** [comment]
Awesome, enjoy! let me know if there is anything I can do to help.
